// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateMesocycleRequest = { name: string; mode: MesocycleModeInput };

export type ExerciseType =
  | "Bodyweight"
  | "WeightedBodyweight"
  | "AssistedBodyweight"
  | "Weighted";

/**
 * Input enum mirroring [`ExerciseType`].
 */
export type ExerciseTypeInput =
  | "Bodyweight"
  | "WeightedBodyweight"
  | "AssistedBodyweight"
  | "Weighted";

/**
 * The transposed plan grid: structure is defined once per mesocycle
 * (`microcycles` are the columns, `workouts` and their `planned_exercises` the
 * rows) and prescription varies per week via each planned exercise's `prescriptions`.
 */
export type FullMesocycle = {
  id: number;
  name: string;
  mode: MesocycleMode;
  microcycles: Array<FullMicrocycle>;
  workouts: Array<FullWorkout>;
};

export type FullMicrocycle = {
  id: number;
  position: number;
  phase: Phase | null;
};

export type FullPlannedExercise = {
  id: number;
  exercise: LibraryExercise;
  position: number;
  prescriptions: Array<Prescription>;
};

export type FullWorkout = {
  id: number;
  name: string;
  position: number;
  planned_exercises: Array<FullPlannedExercise>;
};

/**
 * The one prescription that drives a set group, drawn from two mutually
 * exclusive families: proximity-to-failure (`Rir`/`Rpe`) or weight-resolving
 * (`PercentOneRepMax`/`TargetWeight`/`WeightIncrement`). Effort and weight are
 * never prescribed together.
 */
export type Intensity =
  | { "Rir": Rir }
  | { "Rpe": Rpe }
  | { "PercentOneRepMax": PercentOneRepMax }
  | { "TargetWeight": Weight }
  | { "WeightIncrement": Weight };

/**
 * Input enum mirroring [`Intensity`].
 */
export type IntensityInput =
  | { "Rir": number }
  | { "Rpe": number }
  | { "PercentOneRepMax": number }
  | { "TargetWeight": WeightInput }
  | { "WeightIncrement": WeightInput };

export type LibraryExercise = {
  id: number;
  name: Name;
  exercise_type: ExerciseType;
  primary_muscle_group: MuscleGroup;
  secondary_muscle_groups: Array<MuscleGroup>;
};

/**
 * A library exercise's fields, used for both creating and updating. Secondary
 * muscle groups default to empty when the field is omitted.
 */
export type LibraryExerciseRequest = {
  name: string;
  exercise_type: ExerciseTypeInput;
  primary_muscle_group: MuscleGroupInput;
  secondary_muscle_groups?: Array<MuscleGroupInput>;
};

export type Mesocycle = { id: number; name: Name; mode: MesocycleMode };

export type MesocycleMode = "Algorithmic" | "Manual";

/**
 * Input enum mirroring [`MesocycleMode`].
 */
export type MesocycleModeInput = "Algorithmic" | "Manual";

export type MesocycleRow = {
  id: number;
  name: string;
  mode: MesocycleMode;
  microcycle_count: number;
};

export type Microcycle = { id: number; position: number; phase: Phase | null };

/**
 * A muscle a [`LibraryExercise`] trains. An exercise names one as its primary
 * mover and any number of secondaries, so planned volume can be attributed
 * across muscles when building per-muscle set counts.
 */
export type MuscleGroup =
  | "Chest"
  | "Back"
  | "Traps"
  | "Shoulders"
  | "Quads"
  | "Hamstrings"
  | "Glutes"
  | "Biceps"
  | "Triceps"
  | "Calves";

/**
 * Input enum mirroring [`MuscleGroup`].
 */
export type MuscleGroupInput =
  | "Chest"
  | "Back"
  | "Traps"
  | "Shoulders"
  | "Quads"
  | "Hamstrings"
  | "Glutes"
  | "Biceps"
  | "Triceps"
  | "Calves";

export type Name = string;

export type PercentOneRepMax = number;

export type Phase = "Accumulation" | "Intensification" | "Deload";

/**
 * Input enum mirroring [`Phase`].
 */
export type PhaseInput = "Accumulation" | "Intensification" | "Deload";

export type PlannedExercise = {
  id: number;
  exercise: LibraryExercise;
  position: number;
};

/**
 * Which library exercise to place into a workout.
 */
export type PlannedExerciseRequest = { library_exercise_id: number };

/**
 * The set type of a `Prescribed` set group — one that fixes its own reps and
 * intensity. `MyorepMatch` is deliberately excluded: it has no prescription,
 * so it lives as a [`SetGroupType`] variant rather than a set type.
 */
export type PrescribedSetType = "Regular" | "Myorep" | "Drop";

/**
 * Input enum mirroring [`PrescribedSetType`].
 */
export type PrescribedSetTypeInput = "Regular" | "Myorep" | "Drop";

/**
 * The set groups prescribed for one planned exercise in one microcycle — one
 * cell of the plan grid.
 */
export type Prescription = {
  microcycle_id: number;
  set_groups: Array<SetGroup>;
};

/**
 * The desired ordering of a parent's children, by id. Shared by every reorder
 * endpoint.
 */
export type ReorderRequest = { ordered_ids: Array<number> };

/**
 * A single rep count, guaranteed to be at least 1.
 */
export type RepCount = number;

/**
 * A closed rep range, guaranteed to satisfy `1 <= min < max`.
 */
export type RepRange = { min: number; max: number };

/**
 * A planned rep prescription: a single count, a closed `[min, max]` range, or
 * an open-ended `at least n` (AMRAP) target. Each variant carries a validated
 * newtype, so an invalid `RepTarget` is unrepresentable even though the
 * variants themselves are public.
 */
export type RepTarget = { "Exact": RepCount } | { "Range": RepRange } | {
  "AtLeast": RepCount;
};

/**
 * Input enum mirroring [`RepTarget`].
 */
export type RepTargetInput = { "Exact": number } | {
  "Range": { min: number; max: number };
} | { "AtLeast": number };

export type Rir = number;

export type Rpe = number;

/**
 * A planned prescription within a `PlannedExercise`: a uniform block of
 * `number_of_sets` sets. What each set targets depends on the group's
 * [`SetGroupType`]. Per-set divergence is a tracking concern, not part of the
 * plan.
 */
export type SetGroup = {
  id: number;
  position: number;
  number_of_sets: number;
  set_group_type: SetGroupType;
};

export type SetGroupRequest = {
  number_of_sets: number;
  set_group_type: SetGroupTypeInput;
};

/**
 * What the sets in a [`SetGroup`] target. A `Prescribed` group fixes its own
 * reps and intensity up front; a `MyorepMatch` group instead derives them at
 * execution from the preceding regular set, so it carries no prescription of
 * its own — making "a MyorepMatch with its own reps/intensity" unrepresentable.
 */
export type SetGroupType = {
  "Prescribed": {
    set_type: PrescribedSetType;
    reps: RepTarget;
    intensity: Intensity;
  };
} | "MyorepMatch";

/**
 * Input enum mirroring [`SetGroupType`].
 */
export type SetGroupTypeInput = {
  "Prescribed": {
    set_type: PrescribedSetTypeInput;
    reps: RepTargetInput;
    intensity: IntensityInput;
  };
} | "MyorepMatch";

export type UpdateMesocycleRequest = { name: string; mode: MesocycleModeInput };

/**
 * A microcycle's phase. `null` clears it.
 */
export type UpdatePhaseRequest = { phase: PhaseInput | null };

export type Weight = { value: number; unit: WeightUnit };

export type WeightInput = { value: number; unit: WeightUnitInput };

export type WeightUnit = "Kg" | "Lbs";

export type WeightUnitInput = "Kg" | "Lbs";

export type Workout = { id: number; name: Name; position: number };

/**
 * A workout's name, used for both creating and renaming.
 */
export type WorkoutNameRequest = { name: string };
