import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:structure/src/bridge/dto/planning.dart';
import 'package:structure/src/bridge/api/microcycles.dart' as bridge_micro;
import 'package:structure/src/bridge/api/workouts.dart' as bridge_workout;
import 'package:structure/src/bridge/api/exercises.dart' as bridge_planned;

class MesocycleGrid {
  final int mesocycleId; //platformint or just int? flutter says "platformint is primarily for autogenerated code, not intended for developers"
  final List<MesocycleGridRow> rows;

  const MesocycleGrid({required this.mesocycleId, required this.rows});

  int get columnCount => rows.isEmpty ? 0 : rows.first.cells.length;
}

class MesocycleGridRow {
  final MicrocycleDTO microcycle;
  final List<MesocycleGridCell> cells;

  const MesocycleGridRow({required this.microcycle, required this.cells});
}

class MesocycleGridCell {
  final WorkoutDTO workout;
  final List<PlannedExerciseDTO> plannedExercises;

  const MesocycleGridCell({
    required this.workout,
    required this.plannedExercises,
  });
}

final mesocycleGridProvider = FutureProvider.autoDispose
    .family<MesocycleGrid, int>((ref, mesocycleId) async {
      final microcycles = bridge_micro.listMicrocycles(mesocycleId: mesocycleId)
        ..sort((a, b) => a.position.compareTo(b.position));

      final rows = <MesocycleGridRow>[];
      for (final micro in microcycles) {
        final workouts = bridge_workout.listWorkouts(microcycleId: micro.id)
          ..sort((a, b) => a.position.compareTo(b.position));

        final cells = <MesocycleGridCell>[];
        for (final workout in workouts) {
          final planned = bridge_planned.listPlannedExercises(
            workoutId: workout.id,
          )..sort((a, b) => a.position.compareTo(b.position));
          cells.add(
            MesocycleGridCell(workout: workout, plannedExercises: planned),
          );
        }
        rows.add(MesocycleGridRow(microcycle: micro, cells: cells));
      }

      return MesocycleGrid(mesocycleId: mesocycleId, rows: rows);
    });
