//! Writes the web client's TypeScript types from the Rust types this server
//! actually serializes and deserializes, so the two cannot disagree: the bindings
//! in `web/src/api/wire.ts` are generated by the test below, committed, and
//! checked for staleness by `npm run verify`.
//!
//! Only the types a route names appear here. Each is a *root* — `export_all`
//! follows a root's fields into its dependencies — so this list is the wire
//! surface, and a type that no endpoint mentions is not part of it.

use structure_core::domain::planning::{
    LibraryExercise, Mesocycle, Microcycle, PlannedExercise, SetGroup, Workout,
};
use structure_core::persistence::aggregates::FullMesocycle;
use structure_core::persistence::mesocycles::MesocycleRow;
use ts_rs::{Config, TS};

use crate::dto::{
    CreateMesocycleRequest, LibraryExerciseRequest, PlannedExerciseRequest, ReorderRequest,
    SetGroupRequest, UpdateMesocycleRequest, UpdatePhaseRequest, WorkoutNameRequest,
};

/// The web client reads ids as JSON numbers, which is what `serde_json` writes;
/// ts-rs would otherwise render `i64` as `bigint`, a type no response can hold.
const LARGE_INT: &str = "number";

const OUT_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../web/src/api");

#[test]
fn writes_the_web_clients_wire_types() {
    let config = Config::new()
        .with_large_int(LARGE_INT)
        .with_out_dir(OUT_DIR);

    export::<MesocycleRow>(&config);
    export::<Mesocycle>(&config);
    export::<FullMesocycle>(&config);
    export::<Microcycle>(&config);
    export::<Workout>(&config);
    export::<PlannedExercise>(&config);
    export::<SetGroup>(&config);
    export::<LibraryExercise>(&config);

    export::<CreateMesocycleRequest>(&config);
    export::<UpdateMesocycleRequest>(&config);
    export::<UpdatePhaseRequest>(&config);
    export::<WorkoutNameRequest>(&config);
    export::<PlannedExerciseRequest>(&config);
    export::<LibraryExerciseRequest>(&config);
    export::<SetGroupRequest>(&config);
    export::<ReorderRequest>(&config);
}

fn export<T: TS + 'static>(config: &Config) {
    T::export_all(config)
        .unwrap_or_else(|error| panic!("exporting {}: {error}", std::any::type_name::<T>()));
}
