/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevWorkbenchRouteImport } from './routes/dev.workbench'
import { Route as MesocyclesIdRouteImport } from './routes/mesocycles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevWorkbenchRoute = DevWorkbenchRouteImport.update({
  id: '/dev/workbench',
  path: '/dev/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const MesocyclesIdRoute = MesocyclesIdRouteImport.update({
  id: '/mesocycles/$id',
  path: '/mesocycles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/workbench': typeof DevWorkbenchRoute
  '/mesocycles/$id': typeof MesocyclesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/workbench': typeof DevWorkbenchRoute
  '/mesocycles/$id': typeof MesocyclesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/workbench': typeof DevWorkbenchRoute
  '/mesocycles/$id': typeof MesocyclesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev/workbench' | '/mesocycles/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev/workbench' | '/mesocycles/$id'
  id: '__root__' | '/' | '/dev/workbench' | '/mesocycles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevWorkbenchRoute: typeof DevWorkbenchRoute
  MesocyclesIdRoute: typeof MesocyclesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/workbench': {
      id: '/dev/workbench'
      path: '/dev/workbench'
      fullPath: '/dev/workbench'
      preLoaderRoute: typeof DevWorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesocycles/$id': {
      id: '/mesocycles/$id'
      path: '/mesocycles/$id'
      fullPath: '/mesocycles/$id'
      preLoaderRoute: typeof MesocyclesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevWorkbenchRoute: DevWorkbenchRoute,
  MesocyclesIdRoute: MesocyclesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
